### ISSUE TITLE
Plug in Failed to Load - Gramps 5.1.4 AIO - No module named 'typing'`

### ISSUE THREAD

**Issue by brucejackson** [DavidMStraub/gramps-web-sync#1]
**Desktop Environment**
```
GRAMPS: AIO64-5.1.4-1 
Python: 3.6.4 (default, Jan 23 2018, 13:17:37)  ... 
BSDDB: 6.1.0 (6, 0, 30) 
sqlite: 3.21.0 (2.6.0)
LANG: en_GB.UTF-8
OS: Windows

```
**Gramp_webapi**
`"gramps": {"version": "5.1.4"}, "gramps_webapi": {"schema": "0.2.1", "version": "0.2.1"}, `

I downloaded the webapisync plugin into my add-ons directory.  Restarted Gramps.  I attempted to run the plugin and received the following error message.  I rebooted my machine and attempted again.  I received the same error message.  I downloaded the plugin again and repeated the process.  Same error message. 

![image](https://user-images.githubusercontent.com/1219029/138755914-f1fd711f-5d2a-4d07-a323-dcd56ecfb2e3.png)

Note:  I did not attempt the optional step to install `keyring `as I figured it wouldn't work on the Windows AIO version of Gramps.

I have this error message in my gramps51.log file:
`2021-10-25 15:13:17.633: WARNING: _manager.py: line 308: Plugin error (from 'webapisync'): No module named 'typing'`

**Comment by fordprefect480** [comment]
I have the same issue running:
```
GRAMPS: AIO64-5.1.5-1 
Python: 3.6.4 (default, Jan 23 2018, 13:17:37)  ... 
BSDDB: 6.1.0 (6, 0, 30) 
sqlite: 3.21.0 (2.6.0)
LANG: en_GB.UTF-8
OS: Windows
```

@brucejackson's workaround got me past this point (thanks!), but now I get an error when I actually perform a sync:
```
727145: ERROR: grampsapp.py: line 174: Unhandled exception
Traceback (most recent call last):
  File "C:\Users\owens\AppData\Roaming\gramps\gramps51\plugins\gramps-addon-webapisync-main\webapisync.py", line 206, in prepare
    self.confirmation.prepare(self.actions)
  File "C:\Users\owens\AppData\Roaming\gramps\gramps51\plugins\gramps-addon-webapisync-main\webapisync.py", line 719, in prepare
    gid = obj1.gramps_id
AttributeError: 'Tag' object has no attribute 'gramps_id'
```

Any ideas? I can spin off to another issue if you prefer.

**Comment by DavidMStraub** [comment]
Yes that's an issue with the plugin, not with AIO. Can you open an issue at https://github.com/DavidMStraub/gramps-addon-webapisync/ please?

**Comment by fordprefect480** [comment]
#6 created.

**Comment by DavidMStraub** [comment]
This is resolved in latest AIO builds :partying_face:
