### ISSUE TITLE
Images with same filenames and content can be stored as duplicate objects/records

### ISSUE THREAD

**Issue by dsoprea** [DavidMStraub/gramps-web-sync#21]
![image](https://github.com/DavidMStraub/gramps-web-sync/assets/715626/1e705a0f-6d2a-4e5d-b1c1-fae282775c4a)

Both an archive and a sync were used to upload them.

**Comment by dsoprea** [comment]
Actually, it looks like, for each group of three, one has a thumbnail but no link, one has a link but no thumbnail, and one has both a thumbnail and a link. This holds for at least four of the groups near the top.

**Comment by DavidMStraub** [comment]
What do you mean my "a thumbnail" or "a link"? You could look at the raw JSON response (dev tools) to see how the media objects differ.

In general, a sync will not duplicate a media object *unless* the handles are different. An import might well lead to duplicates if they are already there.

**Comment by dsoprea** [comment]
"Thumbnail" means it shows a picture preview under that asset. "Link" means that it shows an associated, clickable person underneath.

**Comment by dsoprea** [comment]
So, the takeaway is just to always sync and never import if the account is non-empty.

**Comment by DavidMStraub** [comment]
Yes, sort of. The import function is still useful to import additional data, e.g. from a GEDCOM somebody has shared with you. Any suggestions to improve the documentation at https://github.com/gramps-project/web to make this clearer are highly welcome.
