### ISSUE TITLE
First-run wizard doesn't appear 

### ISSUE THREAD

**Issue by Dan-cer** [DavidMStraub/gramps-web-sync#28]
Yesterday I had many issues with getting docker-compose started. There were many error messages, when execute `docker-compose up -d`, mostly with port issues.

However, today I could somehow get to this output of `docker-compose up -d`:
`rainer@Optiplex:/var/www/html$ docker-compose up -d
grampsweb_redis is up-to-date
html_grampsweb_1 is up-to-date
grampsweb_celery is up-to-date`

Maybe because today it wasn't the first run of that command NO first-run wizard appeared to start with.
How can I get it now, quasi retroactively?

Thank you for your answer!

**Comment by DavidMStraub** [comment]
Sorry, but this has nothing to do with the Gramps Web Sync Addon. Please see https://www.grampsweb.org/help/ for ways to get community help with Gramps Web setup issues.
