### ISSUE TITLE
media download: folder not found

### ISSUE THREAD

**Issue by dyeopensource** [DavidMStraub/gramps-web-sync#29]
Exported data from existing gramps database (media files were stored in several subfolders, leading to different relativ paths for the media files).
Imported the data on another machine.
Set up Gramps Web server on a Raspberry Pi on the local network. 
Did sync with the newly imported data: Gramps Web server had the files on disk in the folder structure similar to what I had on the original machine (several subfolders - although files added in Gramps Web do not create subfolders).
Finally created a new gramps family tree on another machine, started to sync. Media sync failed, because the path was not found.
I tried to solve the issue, looked at the code.
grampswebsync.py: path = media_path_full(self.db1, obj.get_path()) correctly returns an absolute path inside the Pictures folder (with subfolders in it), but self.api.download_media_file(handle=handle, path=path) fails because the folder does not exist.
I added creation of the folder structure between these 2 lines, i.e. Path(os.path.dirname(path)).mkdir(parents=True, exist_ok=True)
This solved my issue (although did not test further).
First I submitted the issue here: https://gramps-project.org/bugs/view.php?id=13311
Thanks for your work, I really enjoy this addon.

**Comment by DavidMStraub** [comment]
Please see the documentation here about relative media paths: https://www.grampsweb.org/user-guide/import/. Gramps Web does not work with absolute media paths because you can't assume they exist on both machines, and also because of its security implications.

**Comment by dyeopensource** [comment]
> Please see the documentation here about relative media paths: https://www.grampsweb.org/user-guide/import/. Gramps Web does not work with absolute media paths because you can't assume they exist on both machines, and also because of its security implications.

Clear. Thx.
