### ISSUE TITLE
Synced Files Broken in Web Frontend, Showing Full Path in Name

### ISSUE THREAD

**Issue by Geektasticdad** [DavidMStraub/gramps-web-sync#33]
I'm fairly new to Gramps, but I set up the Gramps app and then spun up a docker container running Gramps Web Frontend. I want to use the app to make updates and then sync them to the web UI so I can invite family to view. Problem is, when I run the sync, the filenames that get uploaded show the full file path. 

When I set up the family tree, I used a different Database, Backup, and Media path, and I did this so the changes will sync to my OneDrive backups.

**Database Path:** C:\Users\<user>\OneDrive\Documents\Gramps
**Backups Path:** C:\Users\<user>\OneDrive\Documents\Gramps\Backups
**Base Media Path:** c:\users\<user>\onedrive\Documents\Gramps\Media

The media I have is just in the root base media path, so the filenames would be something like "29665468_10215735084633126_6974925612187432103_o.jpg"

When I run the sync, they upload the file name as this "C:\Users\<user>\OneDrive\Documents\Family Tree\Family Tree_media\29665468_10215735084633126_6974925612187432103_o.jpg" (note that this whole thing is the filename, see below). 

![image](https://github.com/user-attachments/assets/c7d927b2-a51b-4d85-a75d-d4953fe364a2)

I'm curious what I am doing wrong? 

**System Info for Gramps Web:**
Gramps 5.2.2
Gramps Web API 2.4.2
Gramps Web Frontend 24.8.0
Gramps QL 0.3.0
locale: en
multi-tree: false
task queue: true

**System Info for Gramps App:**
GRAMPS: AIO64-5.2.3-r1-aa03f5a 
Python: 3.11.9 
BSDDB: 6.2.9 (6, 0, 30) 
sqlite: 3.46.0 (2.6.0)
LANG: en_US.UTF-8
OS: Windows

Gramps Web Sync v1.1.1

**Comment by Geektasticdad** [comment]
Okay quick update, I ran a Check and Repair of my database the ran the sync. File names are still wonky, but they aren't broken now. Is this normal behavior?

**Comment by DavidMStraub** [comment]
Hi,

please see the documentation https://www.grampsweb.org/user-guide/import/: when using Gramps Web, you should make sure you don't have any absolute media paths as these won't work on the server. Let me know if that resolves your problem.

**Comment by Geektasticdad** [comment]
> Hi,
> 
> please see the documentation https://www.grampsweb.org/user-guide/import/: when using Gramps Web, you should make sure you don't have any absolute media paths as these won't work on the server. Let me know if that resolves your problem.

Thank you, they are all relative. The images are working in web now, but the file names are still strange (the file name is basically the entire local path). Just curious if that's the expected behavior?

**Comment by DavidMStraub** [comment]
Where do you see the file name?

**Comment by Geektasticdad** [comment]
> Where do you see the file name?

It's on a Debian server running docker with the Gramps web container.

**Comment by DavidMStraub** [comment]
I mean where in the frontend. A screenshot would help.

**Comment by DavidMStraub** [comment]
I don't see a full path in this picture.
