### ISSUE TITLE
Add Ukrainian localization

### ISSUE THREAD

**Issue by Illia-M** [DavidMStraub/gramps-web-sync#35]
Hi! I'm trying promote Gramps in Ukraine for local researchers and want add more Ukrainian in Gramps - can I add translation?

**Comment by DavidMStraub** [comment]
That would be awesome! You can also directly submit a pull request to https://github.com/gramps-project/addons-source/ if you like.

**Comment by Illia-M** [comment]
Okay, then I will try add it to shared repository with all addons, thank you!)

**Comment by Illia-M** [comment]
And I want to sincerely thank you @DavidMStraub for your work – this project is incredible, and your add-on is truly invaluable.
